spring:
  application:
    name: spring-session-redis

  session:
    redis:
      repository-type: indexed
      flush-mode: on-save
      configure-action: none
      save-mode: on-set-attribute
      cleanup-cron: 0 * * * * *
      namespace: spring:session
    timeout: 30m
  data:
    redis:
      client-type: lettuce
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 1000
      timeout: 1000
      lettuce:
        shutdown-timeout: 100ms
logging:
  level:
    org.springframework.session: trace
    org.springframework.data.redis: trace
    org.springframework.security: trace

server:
  error:
    whitelabel:
      enabled: true
    include-binding-errors: never
    include-message: never
    include-stacktrace: never
    include-exception: false
    include-path: never