spring:
  application:
    name: spring-session-redis
  session:
    redis:
      repository-type: indexed
      flush-mode: on-save
      configure-action: none
      save-mode: on-set-attribute
      cleanup-cron: 0 * * * * *
      namespace: spring:session
    timeout: 1h
  data:
    redis:
      client-type: lettuce
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 1000
      timeout: 1000
      lettuce:
        shutdown-timeout: 100ms
  mustache:
    servlet:
      content-type: text/html;charset=UTF-8
      cache: false
      allow-session-override: false
      allow-request-override: false
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: true
    charset: UTF-8
    suffix: .mustache
    prefix: classpath:/templates/
    check-template-location: true
    enabled: true
    view-names: '*'

logging:
  level:
    org.springframework.session: trace
    org.springframework.data.redis: trace
    org.springframework.security: trace

server:
  error:
    whitelabel:
      enabled: true
    include-binding-errors: never
    include-message: never
    include-stacktrace: never
    include-exception: false
    include-path: never
